name: CI
on: [push]
jobs:
    lighthouseci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: '14'
            - run: yarn --frozen-lockfile
            - run: yarn build
            - run: yarn lighthouse
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: '14'
            - run: yarn --frozen-lockfile
            - run: yarn lint
